name: portfolio-nextjs

services:
  nextjs:
    type: node:20
    command: npm run dev
    ports:
      - "3001:3000"
      - "9000:9000"

tooling:
  npm:
    service: nextjs
  npx:
    service: nextjs
